# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0003_auto_20161212_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 12, 8, 0, 6, 634616, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='algae',
            field=models.CharField(blank=True, choices=[('', 'Not noted'), ('NONE', 'None'), ('SURFACES', "It's on surfaces"), ('SUSPENDED', "It's in the water")], max_length=12),
        ),
        migrations.AlterField(
            model_name='observation',
            name='calcium_hardness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cyuranic_acid',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='free_chlorine',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phosphate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='test_type',
            field=models.CharField(blank=True, choices=[('', 'Not noted'), ('REAGENT', 'Chemical reagent kit'), ('STRIP', 'Strip test'), ('PHOTOMETER', 'Reagent + Photometer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='observation',
            name='total_chlorine',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='total_dissolved_solids',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
