# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0004_auto_20161212_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
