# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0005_auto_20161212_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='free_chlorine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phosphate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='total_chlorine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
