# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0007_auto_20161215_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='total_alkalinity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
