# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0008_observation_total_alkalinity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('construction_type', models.CharField(blank=True, choices=[('', 'Not noted'), ('VINYL', 'Vinyl lined, in-ground or buried in-ground'), ('TILED', 'Tiled'), ('CONCRETE', 'Concrete formed'), ('FIBERGLASS', 'Fiberglass')], max_length=12)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, choices=[('', 'Not noted'), ('METRIC', 'Metric / SI'), ('IMPERIAL', 'Imperial')], max_length=12)),
                ('filtration', models.CharField(blank=True, choices=[('', 'Not noted'), ('SAND', 'Sand filter'), ('CARTRIDGES', 'Cartridge filter')], max_length=12)),
                ('sanitizer', models.CharField(blank=True, choices=[('', 'Not noted'), ('CHLORINE', 'Chlorine dosing'), ('BROMINE', 'Bromine dosing'), ('SALT', 'Salt dosing with chlorine generator')], max_length=12)),
                ('heater', models.CharField(blank=True, choices=[('', 'Not noted'), ('NONE', 'None'), ('SOLAR', 'Active solar heating'), ('GAS', 'Gas fired heater'), ('ELECTRIC', 'Electrically heated')], max_length=12)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
