# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacorder', '0009_pool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
